Qgis3.14
carla-simulator/map pull request #31
Opened 2020-10-21 10:02 UTC by shreyadey23

**QGis 2.18 to QGis 3.14**

- - The plugin code is adapted to QGis3.14, Python 3 and the python bindings of the new C++ interface.

  CARLA ad_map_access Plugin was written for QGis 2.18 using manually written python binding calls.
  In the meantime, there existed a 1:1 python binding of the C++ interface.
  The existing code for the plugin was adapted to be compatible with the new C++ interface.
  Also, changes were made to made the plugin code adaptable to QGis version 3.14 
  (Please note: QGis 3.14 had many differences with QGis 2.18 , the details of which can be found at: https://qgis.org/api/api_break.html)

- - QGis-Logger is restored.

  The QGis Logger to display warning, info and error messages inside the tool was restored.

- - Button to enable LaneIDs in view for all layers at once.

  Earlier version of the plugin code required to select each layer and select the attribute to be visible on the loaded map.
  With the help of this feature, the lane IDs of all the loaded layers are visible at once for better and easier map attribute visualization.

- - Settings for Route Prediction test, Routing Test at run time.

  Once the buttons for prediction/routing test are activated, the user gets an option to select the route creation mode, length and duration at run time. 

- - For open drive map, the attributes roadId, laneSectionIndex and laneIndex are added.

  The roadId, Lane Section Index and lane Index are now added as an attribute for open drive maps.

- - The ENU coordinates of the map snapped point is added as an attribute.

  ENU Co-ordinates of the map snapped points is now visible in the Qgis Logger and also as an attribute.

2020-10-22 18:17 UTC, berndgassmann requested changes
> Reviewed 13 of 124 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/map/31)* status: 13 of 124 files reviewed, 15 unresolved discussions (waiting on @shreyadey23)

___
*[startQGis.sh, line 2 at r1](https://reviewable.io/reviews/carla-simulator/map/31#-MKGI2p49CFwgGZ-jOa2:-MKGI2p49CFwgGZ-jOa3:b-r04u81) ([raw file](https://github.com/carla-simulator/map/blob/75740e2fd507aa23bfaa8d69d596624426e5bebf/startQGis.sh#L2)):*
> ```Shell
> #!/bin/bash
> ```

This is not a file for general use. Please remove.
___
*[symbology-style.db, line 0 at r1](https://reviewable.io/reviews/carla-simulator/map/31#-MKGIU8e97cX70i_aEr6:-MKGIU8e97cX70i_aEr7:b-8ajtn8) ([raw file](https://github.com/carla-simulator/map/blob/75740e2fd507aa23bfaa8d69d596624426e5bebf/symbology-style.db#L0)):*
This file is not required and should be removed.
___
*[ad_map_access/impl/include/ad/map/lane/BorderOperation.hpp, line 143 at r1](https://reviewable.io/reviews/carla-simulator/map/31#-MKGIh4k1uPQtYSkUUry:-MKGIh4k1uPQtYSkUUrz:b-dldux) ([raw file](https://github.com/carla-simulator/map/blob/75740e2fd507aa23bfaa8d69d596624426e5bebf/ad_map_access/impl/include/ad/map/lane/BorderOperation.hpp#L143)):*
> ```cpp
> }
> 
> physics::Distance calcLength(ENUBorderList const &borderList);
> ```

please provide some doxygen documentation to these functions
___
*[ad_map_access/impl/include/ad/map/lane/BorderOperation.hpp, line 152 at r1](https://reviewable.io/reviews/carla-simulator/map/31#-MKGIcGy7AD4y01gkRMH:-MKGIcGy7AD4y01gkRMI:b-soii0i) ([raw file](https://github.com/carla-simulator/map/blob/75740e2fd507aa23bfaa8d69d596624426e5bebf/ad_map_access/impl/include/ad/map/lane/BorderOperation.hpp#L152)):*
> ```cpp
>  *  an ENUHeading(2*M_PI) is returned.
>  */
> // point::ENUHeading getENUHeading(std::vector<ENUBorder> const &borderList, point::ENUPoint const &enuPoint);
> ```

remove the commented out version of the function
___
*[ad_map_access/impl/include/ad/map/route/RouteOperation.hpp, line 933 at r1](https://reviewable.io/reviews/carla-simulator/map/31#-MKGIqlo8nNPBU4zP0VR:-MKGIqlo8nNPBU4zP0VS:bbtz53o) ([raw file](https://github.com/carla-simulator/map/blob/75740e2fd507aa23bfaa8d69d596624426e5bebf/ad_map_access/impl/include/ad/map/route/RouteOperation.hpp#L933)):*
> ```cpp
> std::vector<lane::ENUBorder> getENUBorderOfRoute(FullRoute const &route);
> 
> std::vector<lane::ECEFBorder> getECEFBorderOfRoute(FullRoute const &route);
> ```

please provide docu to the functions.
___
*[ad_map_access/impl/src/lane/BorderOperation.cpp, line 22 at r1](https://reviewable.io/reviews/carla-simulator/map/31#-MKGIzom0hpaP_CVBsv7:-MKGIzom0hpaP_CVBsv8:b3946ds) ([raw file](https://github.com/carla-simulator/map/blob/75740e2fd507aa23bfaa8d69d596624426e5bebf/ad_map_access/impl/src/lane/BorderOperation.cpp#L22)):*
> ```cpp
> {
>   physics::Distance total;
>   for (auto value : borderList)
> ```

auto const &value
can be used  to prevent from copies
___
*[ad_map_access/impl/src/lane/BorderOperation.cpp, line 32 at r1](https://reviewable.io/reviews/carla-simulator/map/31#-MKGJ4jv4P8JKzWaDBgJ:-MKGJ4jv4P8JKzWaDBgK:b2583nq) ([raw file](https://github.com/carla-simulator/map/blob/75740e2fd507aa23bfaa8d69d596624426e5bebf/ad_map_access/impl/src/lane/BorderOperation.cpp#L32)):*
> ```cpp
> {
>   physics::Distance total;
>   for (auto value : borderList)
> ```

same as above: make const reference
___
*[ad_map_access/impl/src/lane/BorderOperation.cpp, line 42 at r1](https://reviewable.io/reviews/carla-simulator/map/31#-MKGJ9DAD8dhR0wIvQdQ:-MKGJ9DAD8dhR0wIvQdR:b2583nq) ([raw file](https://github.com/carla-simulator/map/blob/75740e2fd507aa23bfaa8d69d596624426e5bebf/ad_map_access/impl/src/lane/BorderOperation.cpp#L42)):*
> ```cpp
> {
>   physics::Distance total;
>   for (auto value : borderList)
> ```

same as above: make const reference
___
*[ad_map_access/impl/src/route/RouteOperation.cpp, line 2261 at r1](https://reviewable.io/reviews/carla-simulator/map/31#-MKGJGbx66l9spzkB8Ew:-MKGJGby1F5rfRdVO1-z:btbyqfq) ([raw file](https://github.com/carla-simulator/map/blob/75740e2fd507aa23bfaa8d69d596624426e5bebf/ad_map_access/impl/src/route/RouteOperation.cpp#L2261)):*
> ```cpp
> std::vector<lane::ECEFBorder> getECEFBorderOfRoute(FullRoute const &route)
> {
>   std::vector<lane::ECEFBorder> ecefBorderList;
> ```

one runtime optimization could be to call
ecefBorderList.reserve(route.roadSegments.size())
to allocate the required space in the vector at once
maybe you can add this also to the above getENUBorderOfRoute() function
___
*[ad_map_access/impl/src/route/RouteOperation.cpp, line 2272 at r1](https://reviewable.io/reviews/carla-simulator/map/31#-MKGJZEV5IP_Wseps1xx:-MKGJZEV5IP_Wseps1xy:b-ehbxl1) ([raw file](https://github.com/carla-simulator/map/blob/75740e2fd507aa23bfaa8d69d596624426e5bebf/ad_map_access/impl/src/route/RouteOperation.cpp#L2272)):*
> ```cpp
> {
>   std::vector<lane::GeoBorder> geoBorderList;
>   for (auto const &roadSegment : route.roadSegments)
> ```

add reserve() call (see above for details)
___
*[ad_map_access/impl/src/route/RouteOperation.cpp, line 2279 at r1](https://reviewable.io/reviews/carla-simulator/map/31#-MKGJgFy6EttFRQcV1sK:-MKGJgFy6EttFRQcV1sL:bcoos9t) ([raw file](https://github.com/carla-simulator/map/blob/75740e2fd507aa23bfaa8d69d596624426e5bebf/ad_map_access/impl/src/route/RouteOperation.cpp#L2279)):*
> ```cpp
> }
> 
> std::vector<lane::ENUBorder> getENUBorderOfRoute(FullRouteList const &route)
> ```

This function should not be required, remove it. Makes no sense to me to combine the borders of different routes...
___
*[ad_map_access/impl/src/route/RouteOperation.cpp, line 2292 at r1](https://reviewable.io/reviews/carla-simulator/map/31#-MKGJr5mENil5jEQM8vo:-MKGJr5mENil5jEQM8vp:bcoos9t) ([raw file](https://github.com/carla-simulator/map/blob/75740e2fd507aa23bfaa8d69d596624426e5bebf/ad_map_access/impl/src/route/RouteOperation.cpp#L2292)):*
> ```cpp
> }
> 
> std::vector<lane::ECEFBorder> getECEFBorderOfRoute(FullRouteList const &route)
> ```

This function should not be required, remove it. Makes no sense to me to combine the borders of different routes...
___
*[ad_map_access/impl/src/route/RouteOperation.cpp, line 2305 at r1](https://reviewable.io/reviews/carla-simulator/map/31#-MKGJrwDDfvQEI2V1b_M:-MKGJrwDDfvQEI2V1b_N:bcoos9t) ([raw file](https://github.com/carla-simulator/map/blob/75740e2fd507aa23bfaa8d69d596624426e5bebf/ad_map_access/impl/src/route/RouteOperation.cpp#L2305)):*
> ```cpp
> }
> 
> std::vector<lane::GeoBorder> getGeoBorderOfRoute(FullRouteList const &route)
> ```

This function should not be required, remove it. Makes no sense to me to combine the borders of different routes...
___
*[ad_map_access/python/generate_python_lib.py.in, line 41 at r1](https://reviewable.io/reviews/carla-simulator/map/31#-MKGK4Bd6xbr_EtokbWW:-MKGK4Bd6xbr_EtokbWX:b-jaoy0z) ([raw file](https://github.com/carla-simulator/map/blob/75740e2fd507aa23bfaa8d69d596624426e5bebf/ad_map_access/python/generate_python_lib.py.in#L41)):*
> ```
>         # some renaming for set data types
>         ("\"vector_less__ad_scope_map_scope_route_scope_FullRoute__greater_\"", "\"FullRouteList\""),
> 	("\"vector_less__ad_scope_map_scope_lane_scope_ENUBorder__greater_\"", "\"ENUBorderList\""),
> ```

replace tabs by spaces and align indention
___
*[doc/ad_map_access/ad_map_access_python.md.orig, line 1 at r1](https://reviewable.io/reviews/carla-simulator/map/31#-MKGKKO80ifkZzOYFNHZ:-MKGKKO80ifkZzOYFNH_:bwxik8x) ([raw file](https://github.com/carla-simulator/map/blob/75740e2fd507aa23bfaa8d69d596624426e5bebf/doc/ad_map_access/ad_map_access_python.md.orig#L1)):*
> ```
> ## Usage of Python binding for ad_map_access
> ```

some file from a merge? 
Remove.


<!-- Sent from Reviewable.io -->

2020-10-23 07:23 UTC, berndgassmann requested changes
> Reviewed 111 of 124 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/map/31)* status: all files reviewed, 63 unresolved discussions (waiting on @shreyadey23)

___
*[doc/ad_map_access_qgis/ad_map_access_qgis.md, line 36 at r1](https://reviewable.io/reviews/carla-simulator/map/31#-MKJ3b0I7vD38aR_iYNN:-MKJ3b0JDHPCdXk19N2T:bkmre0x) ([raw file](https://github.com/carla-simulator/map/blob/75740e2fd507aa23bfaa8d69d596624426e5bebf/doc/ad_map_access_qgis/ad_map_access_qgis.md#L36)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
> ### Features of QGis 3.14 <a name="features"></a>
> Version 3.0 brings changes to many underlying dependencies which QGIS is built upon.
> #### Python 3.0
> QGIS 3.0 introduces a move to Python 3. This version brings many changes to both the Python language and individual Python libraries.
> A good place to start learning about the changes involved, and how to port your code to Python 3, is available in the official Python documentation: [Porting Python 2 Code to Python 3.](https://docs.python.org/3/howto/pyporting.html)
> #### Qt5
> QGIS 3.0 is based off version 5 of the underlying Qt libraries. Many changes and API breaks were introduced in Qt5.
> #### PyQt 5
> Together with the Python and Qt version changes, the PyQt libraries which expose Qt classes to Python have also had their version bumped to PyQt 5.
> ```
</details>


This is information on the actual changes done/required by this RP. It's not required here. The relevant parts were mentioned in the commit message. This section is of not much value of someone that wants to use the plugin now. Or reads this after the PR was merged.
Since from now on it's built upon QGIS 3.14 it's not relevant from where this code came from; also not relevant how to port from python2-python3.
I'd drop this section here completely.
___
*[doc/ad_map_access_qgis/ad_map_access_qgis.md, line 55 at r1](https://reviewable.io/reviews/carla-simulator/map/31#-MKJ57ti5J6Cqm3My1bq:-MKJ57ti5J6Cqm3My1br:bpel8pr) ([raw file](https://github.com/carla-simulator/map/blob/75740e2fd507aa23bfaa8d69d596624426e5bebf/doc/ad_map_access_qgis/ad_map_access_qgis.md#L55)):*
> ```
> Unload Loaded Map
> ```
copy/paste?
___
*[doc/ad_map_access_qgis/ad_map_access_qgis.md, line 57 at r1](https://reviewable.io/reviews/carla-simulator/map/31#-MKJ5HQN8RgpiHRdLssS:-MKJ5HQO8b_sTaQqDgLP:b-neqk3j) ([raw file](https://github.com/carla-simulator/map/blob/75740e2fd507aa23bfaa8d69d596624426e5bebf/doc/ad_map_access_qgis/ad_map_access_qgis.md#L57)):*
> ```Markdown
>  ![Unload Loaded Map](images/Snappingtest.png) : User can select this icon to activate the snapping test. Also ENU co-ordinates of the map-snapped listed points is also visible. 
> #### Routing Test
>  ![Unload Loaded Map](images/Routingtest.png) : Selecting this icon, will provide the options to the user to select a mode for route creation. After selecting the appropriate route creation mode, the start point and the end point of the route is selected on the map, which then generates the route.
> ```

copy/paste?
___
*[doc/ad_map_access_qgis/ad_map_access_qgis.md, line 59 at r1](https://reviewable.io/reviews/carla-simulator/map/31#-MKJ5DKT5WqY7cBphKYS:-MKJ5DKT5WqY7cBphKYT:bpel8pr) ([raw file](https://github.com/carla-simulator/map/blob/75740e2fd507aa23bfaa8d69d596624426e5bebf/doc/ad_map_access_qgis/ad_map_access_qgis.md#L59)):*
> ```
> Unload Loaded Map
> ```
copy/paste?
___
*[doc/ad_map_access_qgis/ad_map_access_qgis.md, line 61 at r1](https://reviewable.io/reviews/carla-simulator/map/31#-MKJ5G9Z5M0Zbqb4Fki2:-MKJ5G9Z5M0Zbqb4Fki3:b-neqk3j) ([raw file](https://github.com/carla-simulator/map/blob/75740e2fd507aa23bfaa8d69d596624426e5bebf/doc/ad_map_access_qgis/ad_map_access_qgis.md#L61)):*
> ```Markdown
>  ![Unload Loaded Map](images/Routingrestart.png) : User can select this icon to restart the routing test.
> #### Prediction Test
>  ![Unload Loaded Map](images/Predictiontest.png) : Provides the Prediction test on the loaded map. On selecting this icon, user will get options to select the route creation mode, length and duration of the prediction test. Post selection of the test specific features, the lane for prediction can be selected on the map.
> ```

copy/paste?
___
*[doc/ad_map_access_qgis/ad_map_access_qgis.md, line 63 at r1](https://reviewable.io/reviews/carla-simulator/map/31#-MKJ5KyGB0t-rAcLiFJW:-MKJ5KyGB0t-rAcLiFJX:b-neqk3j) ([raw file](https://github.com/carla-simulator/map/blob/75740e2fd507aa23bfaa8d69d596624426e5bebf/doc/ad_map_access_qgis/ad_map_access_qgis.md#L63)):*
> ```Markdown
>  ![Unload Loaded Map](images/Predictiontest.png) : Provides the Prediction test on the loaded map. On selecting this icon, user will get options to select the route creation mode, length and duration of the prediction test. Post selection of the test specific features, the lane for prediction can be selected on the map.
> #### Enable all lane IDs
>  ![Unload Loaded Map](images/ID.png) : Generally it is required to select each layer(INTERSECTION, NORMAL, OTHER or UNKNOWN) under Lane Types, and then activate the lane id attribute to visualize the lane ids on the map. Enabling this button helps the user to bypass those steps, and directly visualize the lane ids on the map. Also, disabling the button removes the lane IDs from the map.
> ```

copy/paste?
___
*[doc/ad_map_access_qgis/ad_map_access_qgis.md, line 67 at r1](https://reviewable.io/reviews/carla-simulator/map/31#-MKJ5lGP29UEtJrVaNfQ:-MKJ5lGP29UEtJrVaNfR:b1ncedd) ([raw file](https://github.com/carla-simulator/map/blob/75740e2fd507aa23bfaa8d69d596624426e5bebf/doc/ad_map_access_qgis/ad_map_access_qgis.md#L67)):*
> ```
> /localdisk/shreyade/map
> ```
don't use your path explicitly. use e.g. $PYTHONPATH:<path/to/>install/ like in the other docu done.
___
*[doc/ad_map_access_qgis/ad_map_access_qgis.md, line 67 at r1](https://reviewable.io/reviews/carla-simulator/map/31#-MKJ6F-o8zlIaQQ5s_7F:-MKJ6F-o8zlIaQQ5s_7G:bhv9s0y) ([raw file](https://github.com/carla-simulator/map/blob/75740e2fd507aa23bfaa8d69d596624426e5bebf/doc/ad_map_access_qgis/ad_map_access_qgis.md#L67)):*
> ```
> /localdisk/shreyade/map/install/ad_physics/lib/python3.6:/localdisk/shreyade/map/tools
> ```
This part should not required! The python library of ad_map_access contains all content from ad_physics, too as of the last PR #23. 
___
*[doc/ad_map_access_qgis/ad_map_access_qgis.md, line 69 at r1](https://reviewable.io/reviews/carla-simulator/map/31#-MKJ6cBS6_0CzcxHLp4D:-MKJ6cBT05JqZ-937rW8:b-9swmdy) ([raw file](https://github.com/carla-simulator/map/blob/75740e2fd507aa23bfaa8d69d596624426e5bebf/doc/ad_map_access_qgis/ad_map_access_qgis.md#L69)):*
> ```Markdown
> *$map> export PYTHONPATH=$PYTHONPATH:/localdisk/shreyade/map/install/ad_map_access/lib/python3.6:/localdisk/shreyade/map/install/ad_physics/lib/python3.6:/localdisk/shreyade/map/tools*
> - Load qgis from the working folder where the python environment was set.
> - The QGIS_PLUGINPATH can be configured optionally as a shell script file to avoid loading the plugin everytime, QGis is opened.
> ```

That's right, but you didn't proivde details here how the QGIS_PLUGINPATH should be configured. After colcon run and installation that's the path (maybe double check this):
QGIS_PLUGINPATH=<path/to/>intall/ad_map_access_qgis/share/qgis/python/plugins
___
*[doc/ad_map_access_qgis/ad_map_access_qgis.md, line 73 at r1](https://reviewable.io/reviews/carla-simulator/map/31#-MKJ8XE_CB33k9Nj2kzS:-MKJ8XEa0vRH3YLwmVSp:bxh2mw3) ([raw file](https://github.com/carla-simulator/map/blob/75740e2fd507aa23bfaa8d69d596624426e5bebf/doc/ad_map_access_qgis/ad_map_access_qgis.md#L73)):*
> ```Markdown
> - The map is loaded using the load map icon on the CARLA ad_map_access toolbar. 
>  ![Loading the desired map](images/Load_file.png "Select the map from the file system") 
>       *Select the map from the file system* 
> ```

Maybe you should provide some words on the file to select? [...]

2020-10-27 14:55 UTC, shreyadey23 reviewed
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/map/31)* status: all files reviewed, 63 unresolved discussions (waiting on @berndgassmann and @shreyadey23)

___
*[startQGis.sh, line 2 at r1](https://reviewable.io/reviews/carla-simulator/map/31#-MKGI2p49CFwgGZ-jOa2:-MKdGZTq0QFlpqKkO8o3:b-896fix) ([raw file](https://github.com/carla-simulator/map/blob/75740e2fd507aa23bfaa8d69d596624426e5bebf/startQGis.sh#L2)):*
<details><summary><i>Previously, berndgassmann wrote…</i></summary><blockquote>

This is not a file for general use. Please remove.
</blockquote></details>

Done.
___
*[symbology-style.db, line  at r1](https://reviewable.io/reviews/carla-simulator/map/31#-MKGIU8e97cX70i_aEr6:-MKdGjA30J5QdGdpZOOe:b-896fix) ([raw file](https://github.com/carla-simulator/map/blob/75740e2fd507aa23bfaa8d69d596624426e5bebf/symbology-style.db#L)):*
<details><summary><i>Previously, berndgassmann wrote…</i></summary><blockquote>

This file is not required and should be removed.
</blockquote></details>

Done.
___
*[ad_map_access/impl/include/ad/map/lane/BorderOperation.hpp, line 143 at r1](https://reviewable.io/reviews/carla-simulator/map/31#-MKGIh4k1uPQtYSkUUry:-MKdGoF5DzY__YlDgT0f:b-896fix) ([raw file](https://github.com/carla-simulator/map/blob/75740e2fd507aa23bfaa8d69d596624426e5bebf/ad_map_access/impl/include/ad/map/lane/BorderOperation.hpp#L143)):*
<details><summary><i>Previously, berndgassmann wrote…</i></summary><blockquote>

please provide some doxygen documentation to these functions
</blockquote></details>

Done.
___
*[ad_map_access/impl/include/ad/map/lane/BorderOperation.hpp, line 152 at r1](https://reviewable.io/reviews/carla-simulator/map/31#-MKGIcGy7AD4y01gkRMH:-MKdGluO8NeH9-uMZ-ec:b-896fix) ([raw file](https://github.com/carla-simulator/map/blob/75740e2fd507aa23bfaa8d69d596624426e5bebf/ad_map_access/impl/include/ad/map/lane/BorderOperation.hpp#L152)):*
<details><summary><i>Previously, berndgassmann wrote…</i></summary><blockquote>

remove the commented out version of the function
</blockquote></details>

Done.
___
*[ad_map_access/impl/include/ad/map/route/RouteOperation.hpp, line 933 at r1](https://reviewable.io/reviews/carla-simulator/map/31#-MKGIqlo8nNPBU4zP0VR:-MKdGpwFEllTyHnXNlDN:b-896fix) ([raw file](https://github.com/carla-simulator/map/blob/75740e2fd507aa23bfaa8d69d596624426e5bebf/ad_map_access/impl/include/ad/map/route/RouteOperation.hpp#L933)):*
<details><summary><i>Previously, berndgassmann wrote…</i></summary><blockquote>

please provide docu to the functions.
</blockquote></details>

Done.
___
*[ad_map_access/impl/src/lane/BorderOperation.cpp, line 22 at r1](https://reviewable.io/reviews/carla-simulator/map/31#-MKGIzom0hpaP_CVBsv7:-MKdGsAO5iTl-ETChJeZ:b-896fix) ([raw file](https://github.com/carla-simulator/map/blob/75740e2fd507aa23bfaa8d69d596624426e5bebf/ad_map_access/impl/src/lane/BorderOperation.cpp#L22)):*
<details><summary><i>Previously, berndgassmann wrote…</i></summary><blockquote>

auto const &value
can be used  to prevent from copies
</blockquote></details>

Done.
___
*[ad_map_access/impl/src/lane/BorderOperation.cpp, line 32 at r1](https://reviewable.io/reviews/carla-simulator/map/31#-MKGJ4jv4P8JKzWaDBgJ:-MKdHAyd9o4r04atnkEP:b-896fix) ([raw file](https://github.com/carla-simulator/map/blob/75740e2fd507aa23bfaa8d69d596624426e5bebf/ad_map_access/impl/src/lane/BorderOperation.cpp#L32)):*
<details><summary><i>Previously, berndgassmann wrote…</i></summary><blockquote>

same as above: make const reference
</blockquote></details>

Done.
___
*[ad_map_access/impl/src/lane/BorderOperation.cpp, line 42 at r1](https://reviewable.io/reviews/carla-simulator/map/31#-MKGJ9DAD8dhR0wIvQdQ:-MKdHBeA-D7CVfZOKBmH:b-896fix) ([raw file](https://github.com/carla-simulator/map/blob/75740e2fd507aa23bfaa8d69d596624426e5bebf/ad_map_access/impl/src/lane/BorderOperation.cpp#L42)):*
<details><summary><i>Previously, berndgassmann wrote…</i></summary><blockquote>

same as above: make const reference
</blockquote></details>

Done.
___
*[ad_map_access/impl/src/route/RouteOperation.cpp, line 2261 at r1](https://reviewable.io/reviews/carla-simulator/map/31#-MKGJGbx66l9spzkB8Ew:-MKdHCSN9t9e6TvL8BgL:b-896fix) ([raw file](https://github.com/carla-simulator/map/blob/75740e2fd507aa23bfaa8d69d596624426e5bebf/ad_map_access/impl/src/route/RouteOperation.cpp#L2261)):*
<details><summary><i>Previously, berndgassmann wrote…</i></summary><blockquote>

one runtime optimization could be to call
ecefBorderList.reserve(route.roadSegments.size())
to allocate the required space in the vector at once
maybe you can add this also to the above getENUBorderOfRoute() function
</blockquote></details>

Done.
___
*[ad_map_access/impl/src/route/RouteOperation.cpp, line 2272 at r1](https://reviewable.io/reviews/carla-simulator/map/31#-MKGJZEV5IP_Wseps1xx:-MKdHCwk45TEYriqvhE6:b-896fix) ([raw file](https://github.com/carla-simulator/map/blob/75740e2fd507aa23bfaa8d69d596624426e5bebf/ad_map_access/impl/src/route/RouteOperation.cpp#L2272)):*
<details><summary><i>Previously, berndgassmann wrote…</i></summary><blockquote>

add reserve() call (see above for details)
</blockquote></details>

Done.
___
*[ad_map_access/impl/src/route/RouteOperation.cpp, line 2279 at r1](https://reviewable.io/reviews/carla-simulator/map/31#-MKGJgFy6EttFRQcV1sK:-MKdHDG_Efj-zKPhOBRe:b-896fix) ([raw file](https://github.com/carla-simulator/map/blob/75740e2fd507aa23bfaa8d69d596624426e5bebf/ad_map_access/impl/src/route/RouteOperation.cpp#L2279)):*
<details><summary><i>Previously, berndgassmann wrote…</i></summary><blockquote>

This function should not be required, remove it. Makes no sense to me to combine the borders of different routes...
</blockquote></details>

Done.
___
*[ad_map_access/impl/src/route/RouteOperation.cpp, line 2292 at r1](https://reviewable.io/reviews/carla-simulator/map/31#-MKGJr5mENil5jEQM8vo:-MKeWuqj1Vq_6MOMyR1W:b-896fix) ([raw file](https://github.com/carla-simulator/map/blob/75740e2fd507aa23bfaa8d69d596624426e5bebf/ad_map_access/impl/src/route/RouteOperation.cpp#L2292)):*
<details><summary><i>Previously, berndgassmann wrote…</i></summary><blockquote>

This function should not be required, remove it. Makes no sense to me to combine the borders of different routes...
</blockquote></details>

Done.
___
*[ad_map_access/impl/src/route/RouteOperation.cpp, line 2305 at r1](https://reviewable.io/reviews/carla-simulator/map/31#-MKGJrwDDfvQEI2V1b_M:-MKeWudWDKX2hSjeY2I5:b-896fix) ([raw file](https://github.com/carla-simulator/map/blob/75740e2fd507aa23bfaa8d69d596624426e5bebf/ad_map_access/impl/src/route/RouteOperation.cpp#L2305)):*
<details><summary><i>Previously, berndgassmann wrote…</i></summary><blockquote>

This function should not be required, remove it. Makes no sense to me to combine the borders of different routes...
</blockquote></details>

Done.
___
*[ad_map_access/python/generate_python_lib.py.in, line 41 at r1](https://reviewable.io/reviews/carla-simulator/map/31#-MKGK4Bd6xbr_EtokbWW:-MKdHIJl55BbY2_N3mHK:b-896fix) ([raw file](https://github.com/carla-simulator/map/blob/75740e2fd507aa23bfaa8d69d596624426e5bebf/ad_map_access/python/generate_python_lib.py.in#L41)):*
<details><summary><i>Previously, berndgassmann wrote…</i></summary><blockquote>

replace tabs by spaces and align indention
</blockquote></details>

Done.
___
*[doc/ad_map_access/ad_map_access_python.md.orig, line 1 at r1](https://reviewable.io/reviews/carla-simulator/map/31#-MKGKKO80ifkZzOYFNHZ:-MKdHJFW0m8EjfM6JyGF:b-896fix) ([raw file](https://github.com/carla-simulator/map/blob/75740e2fd507aa23bfaa8d69d596624426e5bebf/doc/ad_map_access/ad_map_access_python.md.orig#L1)):*
<details><summary><i>Previously, berndgassmann wrote…</i></summary><blockquote>

some file from a merge? 
Remove.
</blockquote></details>

Done.
___
*[doc/ad_map_access_qgis/ad_map_access_qgis.md, line 36 at r1](https://reviewable.io/reviews/carla-simulator/map/31#-MKJ3b0I7vD38aR_iYNN:-MKdH_T6Eshwznph8Qo0:b-896fix) ([raw file](https://github.com/carla-simulator/ [...]

2020-10-28 14:22 UTC, shreyadey23 reviewed
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/map/31)* status: all files reviewed, 63 unresolved discussions (waiting on @berndgassmann and @shreyadey23)

___
*[tools/ad_map_access_qgis/LaneViewer.py, line 20 at r1](https://reviewable.io/reviews/carla-simulator/map/31#-MKJD_6ZCoD8eq04hC2g:-MKihybC8nhu7LBWS7h1:b-896fix) ([raw file](https://github.com/carla-simulator/map/blob/75740e2fd507aa23bfaa8d69d596624426e5bebf/tools/ad_map_access_qgis/LaneViewer.py#L20)):*
<details><summary><i>Previously, berndgassmann wrote…</i></summary><blockquote>

did you actually receive this pylint errors that those had to be disabled? 
By the way: did you run pylint to check for python errors? This helps to identify potential errors in the code...
</blockquote></details>

Done.
___
*[tools/ad_map_access_qgis_python/CMakeLists.txt, line  at r1](https://reviewable.io/reviews/carla-simulator/map/31#-MKJKSpg-1YSV8rpQzdL:-MKjZ7U13SYC4dz4W-Fl:b-896fix) ([raw file](https://github.com/carla-simulator/map/blob/75740e2fd507aa23bfaa8d69d596624426e5bebf/tools/ad_map_access_qgis_python/CMakeLists.txt#L)):*
<details><summary><i>Previously, berndgassmann wrote…</i></summary><blockquote>

You will have to remove also some code from the CMakeLists.txt within ad_map_access_qgis

# and the ad_map_access_qgis_python library is required, so just try to put it in there, too
find_package(ad_map_access_qgis_python QUIET)
if ( ad_map_access_qgis_python_FOUND )
  set(AD_MAP_ACCESS_PYTHON_LIBRARY ${ad_map_access_qgis_python_LIBRARIES})
else()
  get_filename_component(AD_MAP_ACCESS_PYTHON_HINT_BASE ${CMAKE_INSTALL_PREFIX} DIRECTORY)
  find_library(AD_MAP_ACCESS_PYTHON_LIBRARY ad_map_access_qgis_python.so
    HINTS
    ${AD_MAP_ACCESS_PYTHON_HINT_BASE}/ad_map_access_qgis_python/lib/python2.7
    ${CMAKE_INSTALL_PREFIX}/lib/python2.7 )
endif()
if (AD_MAP_ACCESS_PYTHON_LIBRARY)
  get_filename_component(CURRENT_DIR_NAME ${CMAKE_CURRENT_SOURCE_DIR} NAME)
  install(FILES ${AD_MAP_ACCESS_PYTHON_LIBRARY} DESTINATION ${QGIS_PLUGIN_PATH}/${CURRENT_DIR_NAME})
endif()


That code from:
https://github.com/carla-simulator/map/blob/master/tools/ad_map_access_qgis/CMakeLists.txt

is now outdated, because it refers to this deleted library and has to be removed.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-29 16:30 UTC, berndgassmann requested changes
> Reviewed 45 of 47 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/map/31)* status: all files reviewed, 5 unresolved discussions (waiting on @shreyadey23)

___
*[doc/ad_map_access_qgis/ad_map_access_qgis.md, line 57 at r5](https://reviewable.io/reviews/carla-simulator/map/31#-MKp8xKZAf_mZ3rZH4v0:-MKp8xKZAf_mZ3rZH4v1:b5rteie) ([raw file](https://github.com/carla-simulator/map/blob/b06786b49395e0b99f4829f74f8493603b9e0b21/doc/ad_map_access_qgis/ad_map_access_qgis.md#L57)):*
> ```
> g of xodr files is not possible anymore
> ```
didn't this change now again?

Maybe then just say that in addition it is possible to use a txt configuration file to specify some configuration values now by using that feature....
___
*[doc/ad_physics/ad_physics_python.md.orig, line 1 at r1](https://reviewable.io/reviews/carla-simulator/map/31#-MKJBDu01csJ5ZwgSohH:-MKpBOqw6efsVxwuAYfe:b3wkk1k) ([raw file](https://github.com/carla-simulator/map/blob/75740e2fd507aa23bfaa8d69d596624426e5bebf/doc/ad_physics/ad_physics_python.md.orig#L1)):*
<details><summary><i>Previously, shreyadey23 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

looks as if the file is still there?

maybe search for files
find . -name "*.orig" 
so spot addtional left overs...
___
*[tools/ad_map_access_qgis/CMakeLists.txt, line 21 at r5](https://reviewable.io/reviews/carla-simulator/map/31#-MKp9ZDV1E9Zg0iSEcvH:-MKp9ZDW6WxHi88g3sbS:b-kumge9) ([raw file](https://github.com/carla-simulator/map/blob/b06786b49395e0b99f4829f74f8493603b9e0b21/tools/ad_map_access_qgis/CMakeLists.txt#L21)):*
> ```
> /2.18/e
> ```
just spotted the reverence to the old version here...
___
*[tools/ad_map_access_qgis/MapPredictionTest.py, line 131 at r5](https://reviewable.io/reviews/carla-simulator/map/31#-MKpABaG-cQcWm6sT50q:-MKpABaG-cQcWm6sT50r:bsuvcg9) ([raw file](https://github.com/carla-simulator/map/blob/b06786b49395e0b99f4829f74f8493603b9e0b21/tools/ad_map_access_qgis/MapPredictionTest.py#L131)):*
> ```
>         for edge in self.routes_edges:
>             current_prediction_index = len(self.routes_edges) - 1
>             self.layer_routes[current_prediction_index].add_lla2(new_edge.left, new_edge.right, [])
> ```
ah you found an actual error! good. I knew that something was strange with the prediction test layers ...


<!-- Sent from Reviewable.io -->

2020-10-29 17:06 UTC, shreyadey23 reviewed
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/map/31)* status: all files reviewed, 5 unresolved discussions (waiting on @berndgassmann)

___
*[doc/ad_map_access_qgis/ad_map_access_qgis.md, line 57 at r5](https://reviewable.io/reviews/carla-simulator/map/31#-MKp8xKZAf_mZ3rZH4v0:-MKpHgNn50OA5dw8skwD:b-896fix) ([raw file](https://github.com/carla-simulator/map/blob/b06786b49395e0b99f4829f74f8493603b9e0b21/doc/ad_map_access_qgis/ad_map_access_qgis.md#L57)):*
<details><summary><i>Previously, berndgassmann wrote…</i></summary><blockquote>

> ```
> g of xodr files is not possible anymore
> ```
didn't this change now again?

Maybe then just say that in addition it is possible to use a txt configuration file to specify some configuration values now by using that feature....
</blockquote></details>

Done.
___
*[doc/ad_physics/ad_physics_python.md.orig, line 1 at r1](https://reviewable.io/reviews/carla-simulator/map/31#-MKJBDu01csJ5ZwgSohH:-MKpGR1K5C9tps_emsds:blhsw85) ([raw file](https://github.com/carla-simulator/map/blob/75740e2fd507aa23bfaa8d69d596624426e5bebf/doc/ad_physics/ad_physics_python.md.orig#L1)):*
<details><summary><i>Previously, berndgassmann wrote…</i></summary><blockquote>

looks as if the file is still there?

maybe search for files
find . -name "*.orig" 
so spot addtional left overs...
</blockquote></details>


I removed the additional files.
___
*[tools/ad_map_access_qgis/CMakeLists.txt, line 21 at r5](https://reviewable.io/reviews/carla-simulator/map/31#-MKp9ZDV1E9Zg0iSEcvH:-MKpIYI90HDXvxV5X7C8:bn1w4f2) ([raw file](https://github.com/carla-simulator/map/blob/b06786b49395e0b99f4829f74f8493603b9e0b21/tools/ad_map_access_qgis/CMakeLists.txt#L21)):*
<details><summary><i>Previously, berndgassmann wrote…</i></summary><blockquote>

> ```
> /2.18/e
> ```
just spotted the reverence to the old version here...
</blockquote></details>

Old link is not functional anymore. Hence replaced with a new working link.
___
*[tools/ad_map_access_qgis/LaneViewer.py, line 20 at r1](https://reviewable.io/reviews/carla-simulator/map/31#-MKJD_6ZCoD8eq04hC2g:-MKj_eU_49D34YfWSk2C:b-896fix) ([raw file](https://github.com/carla-simulator/map/blob/75740e2fd507aa23bfaa8d69d596624426e5bebf/tools/ad_map_access_qgis/LaneViewer.py#L20)):*
<details><summary><i>Previously, shreyadey23 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.
___
*[tools/ad_map_access_qgis/MapPredictionTest.py, line 131 at r5](https://reviewable.io/reviews/carla-simulator/map/31#-MKpABaG-cQcWm6sT50q:-MKpJkBq3JEl9GbtykSG:b-896fix) ([raw file](https://github.com/carla-simulator/map/blob/b06786b49395e0b99f4829f74f8493603b9e0b21/tools/ad_map_access_qgis/MapPredictionTest.py#L131)):*
<details><summary><i>Previously, berndgassmann wrote…</i></summary><blockquote>

> ```
>         for edge in self.routes_edges:
>             current_prediction_index = len(self.routes_edges) - 1
>             self.layer_routes[current_prediction_index].add_lla2(new_edge.left, new_edge.right, [])
> ```
ah you found an actual error! good. I knew that something was strange with the prediction test layers ...
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-29 17:35 UTC, berndgassmann approved these changes
> Reviewed 7 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/map/31)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-29 19:24 UTC, merged