Update planRoute()
carla-simulator/map pull request #42
Opened 2021-01-08 07:16 UTC by hulk-mk

keeping a check on empty routes. Empty routes returns zero valued routeDistance. Without the proposed check , empty route is returned. To avoid that if() check has been added.

2021-01-11 07:54 UTC, berndgassmann requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/map/42)* status: all files reviewed, 2 unresolved discussions (waiting on @hulk-mk)

___
*[ad_map_access/impl/src/route/Planning.cpp, line 343 at r1](https://reviewable.io/reviews/carla-simulator/map/42#-MQkQDB-5Ur_nlY-tmeP:-MQkQDB0-6FAuvd3EtKI:byu8m9q) ([raw file](https://github.com/carla-simulator/map/blob/11623e989203b20ee24e1787746d738e15264314/ad_map_access/impl/src/route/Planning.cpp#L343)):*
> ```cpp
>     FullRoute route
>       = planRoute(routingStart, createRoutingPoint(mapMatchingResult.lanePoint.paraPoint), routeCreationMode);
>     physics::Distance routeDistance;
> ```

This line of code can be removed, has no effect. Especially it is also root causing the compile errors of some compilers (see also the checks...). Then, I believe we might be able to merge your fix. Thanks.
___
*[ad_map_access/impl/src/route/Planning.cpp, line 345 at r1](https://reviewable.io/reviews/carla-simulator/map/42#-MQkQJBM1D0987EHtlF1:-MQkQJBM1D0987EHtlF2:b-p5egip) ([raw file](https://github.com/carla-simulator/map/blob/11623e989203b20ee24e1787746d738e15264314/ad_map_access/impl/src/route/Planning.cpp#L345)):*
> ```cpp
>     physics::Distance routeDistance;
> 
>     if (route.roadSegments.size() > 0) {
> ```

Hey! Yes. Totally makes sense. Thanks for brining this up.


<!-- Sent from Reviewable.io -->

2021-01-14 11:45 UTC, hulk-mk reviewed
line physics::Distance routeDistance; removed

2021-01-14 11:55 UTC, berndgassmann commented
> line physics::Distance routeDistance; removed

Thanks,
seems like the code formatter is not lucky... 
can you run this and handle the issues, please:

find -iname *.cpp -o -iname *.hpp | xargs clang-format-3.9 -style=file -i

I've uploaded also a script that performs the required changes, too in CARLA main:
https://github.com/carla-simulator/carla/blob/master/Util/Formatting/codeformat.py
just in case you don't spot the issue directly.

just run the codeformat.py script on the file (the correct .clang-format file is already checked in this repository ... don't use the one from the CARLA main; there some other code style is applied)

Sorry for the inconvenience, 
but the checker has issues here.

Or if you don't get it done quickly, I also could do it for you. Just tell me.

2021-01-14 12:16 UTC, hulk-mk reviewed
Yes, that would be really nice of you if you can do that. :)  

> *[Reviewable](https://reviewable.io/reviews/carla-simulator/map/42#-:-MR-ohKK9banfduXYuAy:b9ygs7q)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @berndgassmann)

___
*[ad_map_access/impl/src/route/Planning.cpp, line 343 at r1](https://reviewable.io/reviews/carla-simulator/map/42#-MQkQDB-5Ur_nlY-tmeP:-MR-dW4i1IT6DR_rCrNk:bsugg5) ([raw file](https://github.com/carla-simulator/map/blob/11623e989203b20ee24e1787746d738e15264314/ad_map_access/impl/src/route/Planning.cpp#L343)):*
<details><summary><i>Previously, berndgassmann wrote…</i></summary><blockquote>

This line of code can be removed, has no effect. Especially it is also root causing the compile errors of some compilers (see also the checks...). Then, I believe we might be able to merge your fix. Thanks.
</blockquote></details>

Yes, you are correct. I have just removed it in new commit.
___
*[ad_map_access/impl/src/route/Planning.cpp, line 345 at r1](https://reviewable.io/reviews/carla-simulator/map/42#-MQkQJBM1D0987EHtlF1:-MR-nntZ1iKNSZu2-fQo:b-896fix) ([raw file](https://github.com/carla-simulator/map/blob/11623e989203b20ee24e1787746d738e15264314/ad_map_access/impl/src/route/Planning.cpp#L345)):*
<details><summary><i>Previously, berndgassmann wrote…</i></summary><blockquote>

Hey! Yes. Totally makes sense. Thanks for brining this up.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-14 12:33 UTC, berndgassmann commented
ok, I'll check after lunch

2021-01-14 13:27 UTC, berndgassmann commented
I've fixed code formatting, but I didn't know if and who at all I could append a commit to this.
Therefore I've just created a new PR#43

2021-01-14 15:20 UTC, hulk-mk commented
Ok, thank you so much :)

2021-01-14 16:22 UTC, closed without merging

2021-01-14 16:22 UTC, berndgassmann commented
ok, all moved into #43 
Thanks again for the fix.