Fixes #55: python_wrapper_helper uses CMAKE_CXX_STANDARD
carla-simulator/map pull request #56
Opened 2021-05-12 13:40 UTC by daedric

2021-05-12 14:17 UTC, berndgassmann submitted a review, later dismissed
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/map/56)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @daedric)



<!-- Sent from Reviewable.io -->

2021-05-12 15:25 UTC, daedric reviewed
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/map/56)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @daedric)



<!-- Sent from Reviewable.io -->

2021-05-12 15:28 UTC, daedric reviewed
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/map/56)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @daedric)



<!-- Sent from Reviewable.io -->

2021-05-12 15:45 UTC, berndgassmann requested changes

2021-05-12 15:45 UTC, berndgassmann commented on cmake/python/python_wrapper_helper.py.in
Looks like older versions of compiler/OS have problems with some warnings on cast_xml calls; maybe that was the reason why we didn't update the flags originally.
I tested a bit around locally (ok, only have Ubuntu20.04 where the error isn't occurring), but maybe adding a warning suppression for the parser helps
xml_generator_config.append_cflags("-w")
or less restrictive and directly addressing the spdlog warning explicitly making the problem
xml_generator_config.append_cflags("-Wno-error=invalid-constexpr")

2021-05-12 17:14 UTC, berndgassmann commented on cmake/python/python_wrapper_helper.py.in
just came to my mind, that I could try it be editing the file online.
Let's see what the CI makes out of it.
I LOVE multiple compilers on multiple systems :-)

2021-05-17 07:56 UTC, berndgassmann approved these changes

2021-05-17 07:56 UTC, berndgassmann reviewed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/map/56)* status: all files reviewed, 1 unresolved discussion (waiting on @daedric)



<!-- Sent from Reviewable.io -->

2021-05-17 07:57 UTC, berndgassmann approved these changes
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/map/56)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @daedric)



<!-- Sent from Reviewable.io -->

2021-05-17 07:58 UTC, merged